# Generated by Django 3.0.3 on 2020-03-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='regularpizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_pizza', models.CharField(max_length=100)),
                ('reg_small_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reg_large_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'regularpizza',
                'verbose_name_plural': 'regularpizzas',
            },
        ),
    ]
