# Generated by Django 3.0.3 on 2020-03-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_dinner_platters_pasta_salads_sicilianpizza_subs_toppings'),
    ]

    operations = [
        migrations.CreateModel(
            name='sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=100)),
                ('sub_small_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sub_large_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'sub',
                'verbose_name_plural': 'subs',
            },
        ),
        migrations.RenameModel(
            old_name='dinner_platters',
            new_name='dinner_platter',
        ),
        migrations.RenameModel(
            old_name='salads',
            new_name='salad',
        ),
        migrations.RenameModel(
            old_name='toppings',
            new_name='topping',
        ),
        migrations.DeleteModel(
            name='subs',
        ),
        migrations.AlterModelOptions(
            name='dinner_platter',
            options={'verbose_name': 'dinner_platter', 'verbose_name_plural': 'dinner_platters'},
        ),
        migrations.AlterModelOptions(
            name='salad',
            options={'verbose_name': 'salad', 'verbose_name_plural': 'salads'},
        ),
        migrations.AlterModelOptions(
            name='topping',
            options={'verbose_name': 'topping', 'verbose_name_plural': 'toppings'},
        ),
        migrations.RenameField(
            model_name='salad',
            old_name='salads_name',
            new_name='salad_name',
        ),
        migrations.RenameField(
            model_name='salad',
            old_name='salads_price',
            new_name='salad_price',
        ),
    ]
