# Generated by Django 3.0.3 on 2020-04-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200317_0844'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('numOfProducts', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'cartItems',
                'verbose_name_plural': 'cartItemss',
            },
        ),
    ]
