# Generated by Django 3.0.3 on 2020-04-07 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_cartitems'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitems',
            options={'verbose_name': 'cartItems', 'verbose_name_plural': 'cartItems'},
        ),
        migrations.AlterModelOptions(
            name='pasta',
            options={'verbose_name': 'pasta', 'verbose_name_plural': 'pasta'},
        ),
        migrations.AlterModelOptions(
            name='salad',
            options={'verbose_name': 'salad', 'verbose_name_plural': 'salad'},
        ),
    ]
