# Generated by Django 3.0.3 on 2020-04-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200407_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinner_platter',
            name='productID',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pasta',
            name='productID',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regularpizza',
            name='productID',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salad',
            name='productID',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sicilianpizza',
            name='productID',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sub',
            name='productID',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
