# Generated by Django 3.0.3 on 2020-04-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200409_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='product',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
