# Generated by Django 3.0.3 on 2020-04-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200409_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitems',
            old_name='product',
            new_name='productID',
        ),
        migrations.AddField(
            model_name='cartitems',
            name='productType',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
